// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRq) Reset()         { *m = LoginRq{} }
func (m *LoginRq) String() string { return proto.CompactTextString(m) }
func (*LoginRq) ProtoMessage()    {}
func (*LoginRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRq.Unmarshal(m, b)
}
func (m *LoginRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRq.Marshal(b, m, deterministic)
}
func (m *LoginRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRq.Merge(m, src)
}
func (m *LoginRq) XXX_Size() int {
	return xxx_messageInfo_LoginRq.Size(m)
}
func (m *LoginRq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRq proto.InternalMessageInfo

func (m *LoginRq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRsp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ValidUntil           int64    `protobuf:"varint,3,opt,name=validUntil,proto3" json:"validUntil,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRsp) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRq)(nil), "proto.LoginRq")
	proto.RegisterType((*LoginRsp)(nil), "proto.LoginRsp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x8e, 0x5c, 0xec, 0x3e,
	0x20, 0xd1, 0xa0, 0x42, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x57, 0x90, 0x58, 0x5c, 0x5c, 0x9e,
	0x5f, 0x94, 0x22, 0xc1, 0x04, 0x91, 0x83, 0xf1, 0x95, 0xa2, 0xb8, 0x38, 0x20, 0x46, 0x14, 0x17,
	0x08, 0x49, 0x70, 0xb1, 0x17, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x83, 0x8d, 0xe0, 0x08, 0x82,
	0x71, 0x85, 0x44, 0xb8, 0x58, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0xa0, 0xda, 0x21, 0x1c, 0x21, 0x39,
	0x2e, 0xae, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xd0, 0xbc, 0x92, 0xcc, 0x1c, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0x24, 0x91, 0x24, 0x36, 0xb0, 0x2b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0x13, 0xd7, 0xc6, 0xbb, 0x00, 0x00, 0x00,
}
